-- تشغيل التحديث اللحظي وإضافة سجل نشاط لا يراه إلا مالك النظام.

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null,
  actor_role text not null check (actor_role in ('owner', 'admin')),
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  entity_type text not null,
  entity_id text,
  record_label text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
alter table public.audit_logs enable row level security;
grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists audit_logs_owner_read on public.audit_logs;
create policy audit_logs_owner_read on public.audit_logs for select to authenticated
using (public.is_owner());

create or replace function public.record_staff_activity()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  actor public.profiles%rowtype;
  record_data jsonb;
  item_id text;
  item_label text;
begin
  if auth.uid() is null then return coalesce(new, old); end if;
  select * into actor from public.profiles where id = auth.uid();
  if actor.role not in ('owner', 'admin') then return coalesce(new, old); end if;

  record_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  item_id := coalesce(record_data ->> 'id', record_data ->> 'program', record_data ->> 'slug');
  item_label := case tg_table_name
    when 'groups' then record_data ->> 'name'
    when 'group_media' then record_data ->> 'title'
    when 'news' then record_data ->> 'title'
    when 'slider_items' then record_data ->> 'title'
    when 'resources' then record_data ->> 'title'
    when 'registration_settings' then record_data ->> 'title'
    when 'registrations' then concat('طلب تسجيل رقم ', record_data ->> 'id')
    when 'profiles' then record_data ->> 'full_name'
    else item_id
  end;

  insert into public.audit_logs (actor_id, actor_name, actor_role, action, entity_type, entity_id, record_label)
  values (actor.id, coalesce(nullif(actor.full_name, ''), 'مستخدم إداري'), actor.role, tg_op, tg_table_name, item_id, item_label);
  return coalesce(new, old);
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['profiles','registration_settings','registrations','groups','group_media','news','slider_items','resources']
  loop
    execute format('drop trigger if exists audit_%I_changes on public.%I', table_name, table_name);
    execute format('create trigger audit_%I_changes after insert or update or delete on public.%I for each row execute procedure public.record_staff_activity()', table_name, table_name);
  end loop;
end $$;

do $$
declare table_name text;
begin
  foreach table_name in array array['registration_settings','registrations','groups','group_media','news','slider_items','resources','audit_logs']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = table_name
    ) then
      execute format('alter publication supabase_realtime add table public.%I', table_name);
    end if;
    if table_name <> 'audit_logs' then
      execute format('alter table public.%I replica identity full', table_name);
    end if;
  end loop;
end $$;

select 'Realtime and owner activity log are ready' as result;
