-- مركز كفرأبيل القرآني - مخطط Supabase الأولي
-- شغّل هذا الملف مرة واحدة داخل Supabase > SQL Editor.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'viewer' check (role in ('owner', 'admin', 'viewer')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), 'viewer')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select coalesce(public.current_user_role() in ('owner', 'admin'), false);
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select coalesce(public.current_user_role() = 'owner', false);
$$;

create table if not exists public.site_settings (
  id text primary key check (id = 'contact'),
  phone text not null,
  location_text text not null,
  map_url text not null,
  whatsapp_url text not null,
  facebook_url text not null,
  instagram_url text not null,
  youtube_url text not null,
  updated_at timestamptz not null default timezone('utc', now()),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.registration_settings (
  program text primary key check (program in ('permanent', 'tajweed')),
  title text not null,
  is_open boolean not null default false,
  closed_message text not null default 'التسجيل مغلق حاليًا، وسيُعلن عن موعد فتحه لاحقًا.',
  updated_at timestamptz not null default timezone('utc', now()),
  updated_by uuid references auth.users(id)
);

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(trim(full_name)) between 7 and 120),
  gender text not null check (gender in ('male', 'female')),
  birth_date date not null check (birth_date <= current_date),
  phone text not null check (char_length(trim(phone)) between 8 and 20),
  guardian_name text not null check (char_length(trim(guardian_name)) between 3 and 120),
  program text not null references public.registration_settings(program),
  status text not null default 'new' check (status in ('new', 'reviewed', 'accepted', 'rejected')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists registrations_gender_idx on public.registrations(gender);
create index if not exists registrations_program_idx on public.registrations(program);
create index if not exists registrations_created_at_idx on public.registrations(created_at desc);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name text not null,
  gender text not null check (gender in ('male', 'female')),
  supervisor_name text,
  student_count integer not null default 0 check (student_count >= 0),
  student_ages text,
  establishment text,
  hafiz_count integer not null default 0 check (hafiz_count >= 0),
  tajweed_achievement text,
  average_memorization text,
  achievements text,
  image_url text,
  image_path text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.group_media (
  id uuid primary key default gen_random_uuid(),
  group_id uuid not null references public.groups(id) on delete cascade,
  kind text not null check (kind in ('image', 'file')),
  title text not null,
  file_url text not null,
  file_path text,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.news (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  news_date date not null default current_date,
  image_url text,
  image_path text,
  is_published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.slider_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  year integer check (year between 1900 and 2200),
  alt_text text not null default '',
  image_url text not null,
  image_path text,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.resources (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  file_url text not null,
  file_path text,
  is_published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.video_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  youtube_url text not null,
  youtube_id text not null check (youtube_id ~ '^[A-Za-z0-9_-]{11}$'),
  category text,
  sort_order integer not null default 0,
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id) on delete set null
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null,
  actor_role text not null check (actor_role in ('owner', 'admin')),
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  entity_type text not null,
  entity_id text,
  record_label text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);

do $$
declare table_name text;
begin
  foreach table_name in array array['profiles','site_settings','registrations','groups','news','slider_items','video_items','resources']
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format('create trigger set_%I_updated_at before update on public.%I for each row execute procedure public.set_updated_at()', table_name, table_name);
  end loop;
end $$;

insert into public.registration_settings (program, title, is_open)
values
  ('permanent', 'التسجيل في النادي الدائم', false),
  ('tajweed', 'التسجيل في دورات التجويد', false)
on conflict (program) do nothing;

insert into public.site_settings (id, phone, location_text, map_url, whatsapp_url, facebook_url, instagram_url, youtube_url)
values ('contact', '0777120841', 'إربد — لواء الكورة — كفرأبيل', 'https://maps.app.goo.gl/kMnVGHEGyxCKAeeh9?g_st=aw', 'https://wa.me/962777120841', 'https://www.facebook.com/share/1BbQF7fhoz/', 'https://www.instagram.com/kufrabil_center_quranic/', 'https://www.youtube.com/@kufrabilcenterquranic')
on conflict (id) do nothing;

insert into public.groups (slug, name, gender, supervisor_name, student_count, student_ages, establishment, hafiz_count, tajweed_achievement, average_memorization, achievements, image_url, sort_order)
values
  ('almanar', 'مشروع المنار القرآني', 'male', 'قصي بشارات', 12, 'تُضاف لاحقًا', 'تُضاف لاحقًا', 8, 'تُضاف لاحقًا', 'تُضاف لاحقًا', '8 طلاب من حفاظ كتاب الله', 'assets/images/project-al-manar.jpeg', 10),
  ('almukhbiteen', 'مشروع المخبتين القرآني', 'male', 'محمد عادل', 13, 'مواليد 2011 إلى 2015', 'عام 2023', 1, 'تُضاف لاحقًا', '15 جزءًا', 'حافظ واحد لكتاب الله', 'assets/images/project-al-mukhbiteen.jpeg', 20),
  ('faseeroo', 'مشروع فسيروا القرآني', 'male', 'محمد رائد', 12, 'تُضاف لاحقًا', 'تُضاف لاحقًا', 0, 'تُضاف لاحقًا', 'تُضاف لاحقًا', 'تُضاف إنجازات المجموعة لاحقًا', 'assets/images/project-faseeroo.jpeg', 30),
  ('munibeen', 'مشروع منيبين إليه', 'male', 'بهاء الفقيه', 13, 'تُضاف لاحقًا', 'تُضاف لاحقًا', 0, 'تُضاف لاحقًا', 'تُضاف لاحقًا', 'تُضاف إنجازات المجموعة لاحقًا', null, 40),
  ('ahbaballah', 'مشروع أحباب الله', 'male', 'بهاء الفقيه', 14, 'تُضاف لاحقًا', 'تُضاف لاحقًا', 0, 'تُضاف لاحقًا', 'تُضاف لاحقًا', 'تُضاف إنجازات المجموعة لاحقًا', null, 50),
  ('little-hafiz', 'شعبة الحافظ الصغير', 'female', null, 10, 'تُضاف لاحقًا', 'تُضاف لاحقًا', 0, 'تُضاف لاحقًا', 'تُضاف لاحقًا', 'تُضاف إنجازات الشعبة لاحقًا', 'assets/images/group-little-hafiz-girls.jpeg', 10)
on conflict (slug) do nothing;

insert into public.news (title, body, news_date, is_published)
select 'إقرار مواعيد تخريج النادي الصيفي',
       'تم إقرار مواعيد تخريج المشاركين في النادي الصيفي، حيث تقرر إقامة حفل تخريج الإناث يوم الأحد الموافق 9/8/2026، فيما سيُقام حفل تخريج الذكور يوم الأربعاء الموافق 12/8/2026.',
       '2026-08-09', true
where not exists (select 1 from public.news);

insert into public.slider_items (title, year, alt_text, image_url, sort_order)
select item.title, item.year, item.alt_text, item.image_url, item.sort_order
from (values
  ('تخريج حفاظ كتاب الله', 2025, 'تخريج حفاظ كتاب الله في مركز كفرأبيل القرآني عام 2025', 'assets/images/slider/slide-1.jpg', 10),
  ('تخريج أصغر حافظ بعمر 9 سنوات', 2023, 'تخريج أصغر حافظ لكتاب الله بعمر تسع سنوات عام 2023', 'assets/images/slider/slide-2.jpg', 20),
  ('تخريج حفاظ كتاب الله', 2024, 'تخريج حفاظ كتاب الله في مركز كفرأبيل القرآني عام 2024', 'assets/images/slider/slide-3.jpg', 30),
  ('تكريم أحد حفاظ كتاب الله', 2024, 'تكريم أحد حفاظ كتاب الله في مركز كفرأبيل القرآني عام 2024', 'assets/images/slider/slide-4.jpg', 40),
  ('تخريج أحد حفاظ كتاب الله', 2023, 'تخريج أحد حفاظ كتاب الله في مركز كفرأبيل القرآني عام 2023', 'assets/images/slider/slide-5.jpg', 50),
  ('تخريج النادي الصيفي', 2023, 'تخريج النادي الصيفي في مركز كفرأبيل القرآني عام 2023', 'assets/images/slider/slide-6.jpg', 60),
  ('نشاط لمجموعة الحفاظ', 2016, 'نشاط لمجموعة الحفاظ في مركز كفرأبيل القرآني عام 2016', 'assets/images/slider/slide-7.jpg', 70),
  ('مسابقة نور الوحيين', 2019, 'مسابقة نور الوحيين في مركز كفرأبيل القرآني عام 2019', 'assets/images/slider/slide-8.jpg', 80),
  ('نشاط رياضي مع مركز كفرعوان', 2019, 'نشاط رياضي مشترك بين مركزي كفرأبيل وكفرعوان عام 2019', 'assets/images/slider/slide-9.jpg', 90),
  ('مشاركة طلابنا في المسابقة السنوية', 2016, 'مشاركة طلاب مركز كفرأبيل القرآني في المسابقة السنوية عام 2016', 'assets/images/slider/slide-10.jpg', 100),
  ('تخريج أول حافظ في مشروع المخبتين القرآني', 2026, 'تخريج أول حافظ لكتاب الله في مشروع المخبتين القرآني عام 2026', 'assets/images/slider/slide-11.jpg', 110)
) as item(title, year, alt_text, image_url, sort_order)
where not exists (select 1 from public.slider_items);

alter table public.profiles enable row level security;
alter table public.site_settings enable row level security;
alter table public.registration_settings enable row level security;
alter table public.registrations enable row level security;
alter table public.groups enable row level security;
alter table public.group_media enable row level security;
alter table public.news enable row level security;
alter table public.slider_items enable row level security;
alter table public.video_items enable row level security;
alter table public.resources enable row level security;
alter table public.audit_logs enable row level security;

-- الصلاحيات الأساسية للأدوار؛ تبقى حدود الوصول الفعلية محكومة بسياسات RLS أدناه.
grant usage on schema public to anon, authenticated;
grant select on public.site_settings, public.registration_settings, public.groups, public.group_media, public.news, public.slider_items, public.video_items, public.resources to anon, authenticated;
grant insert, update on public.site_settings to authenticated;
grant insert on public.registrations to anon, authenticated;
grant select, insert, update, delete on public.profiles, public.registration_settings, public.registrations, public.groups, public.group_media, public.news, public.slider_items, public.video_items, public.resources to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

drop policy if exists profiles_read_own on public.profiles;
create policy profiles_read_own on public.profiles for select to authenticated
using (id = auth.uid() or public.is_owner());

drop policy if exists profiles_owner_update on public.profiles;
create policy profiles_owner_update on public.profiles for update to authenticated
using (public.is_owner()) with check (public.is_owner());

drop policy if exists registration_settings_public_read on public.registration_settings;
create policy registration_settings_public_read on public.registration_settings for select to anon, authenticated using (true);

drop policy if exists registration_settings_staff_update on public.registration_settings;
create policy registration_settings_staff_update on public.registration_settings for update to authenticated
using (public.is_staff()) with check (public.is_staff());

drop policy if exists site_settings_public_read on public.site_settings;
create policy site_settings_public_read on public.site_settings for select to anon, authenticated using (true);
drop policy if exists site_settings_owner_insert on public.site_settings;
create policy site_settings_owner_insert on public.site_settings for insert to authenticated with check (public.is_owner());
drop policy if exists site_settings_owner_update on public.site_settings;
create policy site_settings_owner_update on public.site_settings for update to authenticated using (public.is_owner()) with check (public.is_owner());

drop policy if exists registrations_public_insert_when_open on public.registrations;
create policy registrations_public_insert_when_open on public.registrations for insert to anon, authenticated
with check (exists (
  select 1 from public.registration_settings settings
  where settings.program = registrations.program and settings.is_open = true
));

drop policy if exists registrations_staff_all on public.registrations;
create policy registrations_staff_all on public.registrations for all to authenticated
using (public.is_staff()) with check (public.is_staff());

drop policy if exists groups_public_read on public.groups;
create policy groups_public_read on public.groups for select to anon, authenticated
using (is_published = true or public.is_staff());
drop policy if exists groups_staff_all on public.groups;
create policy groups_staff_all on public.groups for all to authenticated
using (public.is_staff()) with check (public.is_staff());

drop policy if exists group_media_public_read on public.group_media;
create policy group_media_public_read on public.group_media for select to anon, authenticated
using (exists (select 1 from public.groups where groups.id = group_media.group_id and (groups.is_published or public.is_staff())));
drop policy if exists group_media_staff_all on public.group_media;
create policy group_media_staff_all on public.group_media for all to authenticated
using (public.is_staff()) with check (public.is_staff());

drop policy if exists news_public_read on public.news;
create policy news_public_read on public.news for select to anon, authenticated
using (is_published = true or public.is_staff());
drop policy if exists news_staff_all on public.news;
create policy news_staff_all on public.news for all to authenticated
using (public.is_staff()) with check (public.is_staff());

drop policy if exists slider_public_read on public.slider_items;
create policy slider_public_read on public.slider_items for select to anon, authenticated
using (is_published = true or public.is_staff());
drop policy if exists slider_staff_all on public.slider_items;
create policy slider_staff_all on public.slider_items for all to authenticated
using (public.is_staff()) with check (public.is_staff());

drop policy if exists resources_public_read on public.resources;
create policy resources_public_read on public.resources for select to anon, authenticated
using (is_published = true or public.is_staff());
drop policy if exists resources_staff_all on public.resources;
create policy resources_staff_all on public.resources for all to authenticated
using (public.is_staff()) with check (public.is_staff());

drop policy if exists video_items_public_read on public.video_items;
create policy video_items_public_read on public.video_items for select to anon, authenticated
using ((is_published = true and deleted_at is null) or public.is_staff());
drop policy if exists video_items_staff_all on public.video_items;
create policy video_items_staff_all on public.video_items for all to authenticated
using (public.is_staff()) with check (public.is_staff());

drop policy if exists audit_logs_owner_read on public.audit_logs;
create policy audit_logs_owner_read on public.audit_logs for select to authenticated
using (public.is_owner());

create or replace function public.record_staff_activity()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  actor public.profiles%rowtype;
  record_data jsonb;
  item_id text;
  item_label text;
begin
  if auth.uid() is null then
    return coalesce(new, old);
  end if;

  select * into actor from public.profiles where id = auth.uid();
  if actor.role not in ('owner', 'admin') then
    return coalesce(new, old);
  end if;

  record_data := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  item_id := coalesce(record_data ->> 'id', record_data ->> 'program', record_data ->> 'slug');
  item_label := case tg_table_name
    when 'groups' then record_data ->> 'name'
    when 'group_media' then record_data ->> 'title'
    when 'news' then record_data ->> 'title'
    when 'slider_items' then record_data ->> 'title'
    when 'video_items' then record_data ->> 'title'
    when 'resources' then record_data ->> 'title'
    when 'registration_settings' then record_data ->> 'title'
    when 'registrations' then concat('طلب تسجيل رقم ', record_data ->> 'id')
    when 'profiles' then record_data ->> 'full_name'
    else item_id
  end;

  insert into public.audit_logs (actor_id, actor_name, actor_role, action, entity_type, entity_id, record_label)
  values (actor.id, coalesce(nullif(actor.full_name, ''), 'مستخدم إداري'), actor.role, tg_op, tg_table_name, item_id, item_label);

  return coalesce(new, old);
end;
$$;

do $$
declare table_name text;
begin
  foreach table_name in array array['profiles','site_settings','registration_settings','registrations','groups','group_media','news','slider_items','video_items','resources']
  loop
    execute format('drop trigger if exists audit_%I_changes on public.%I', table_name, table_name);
    execute format('create trigger audit_%I_changes after insert or update or delete on public.%I for each row execute procedure public.record_staff_activity()', table_name, table_name);
  end loop;
end $$;

-- تفعيل التحديث اللحظي للجداول التي تظهر للزوار ولسجل نشاط المالك.
do $$
declare table_name text;
begin
  foreach table_name in array array['site_settings','registration_settings','registrations','groups','group_media','news','slider_items','video_items','resources','audit_logs']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = table_name
    ) then
      execute format('alter publication supabase_realtime add table public.%I', table_name);
    end if;
    if table_name <> 'audit_logs' then
      execute format('alter table public.%I replica identity full', table_name);
    end if;
  end loop;
end $$;

insert into storage.buckets (id, name, public, file_size_limit)
values ('center-public', 'center-public', true, 10485760)
on conflict (id) do update set public = true, file_size_limit = 10485760;

drop policy if exists center_public_files_read on storage.objects;
create policy center_public_files_read on storage.objects for select to anon, authenticated
using (bucket_id = 'center-public');

drop policy if exists center_staff_files_insert on storage.objects;
create policy center_staff_files_insert on storage.objects for insert to authenticated
with check (bucket_id = 'center-public' and public.is_staff());

drop policy if exists center_staff_files_update on storage.objects;
create policy center_staff_files_update on storage.objects for update to authenticated
using (bucket_id = 'center-public' and public.is_staff())
with check (bucket_id = 'center-public' and public.is_staff());

drop policy if exists center_staff_files_delete on storage.objects;
create policy center_staff_files_delete on storage.objects for delete to authenticated
using (bucket_id = 'center-public' and public.is_staff());

grant execute on function public.current_user_role() to anon, authenticated;
grant execute on function public.is_staff() to anon, authenticated;
grant execute on function public.is_owner() to anon, authenticated;

-- بعد إنشاء الحسابين من Authentication > Users، نفّذ الأوامر الموجودة في SUPABASE_SETUP.md لتحديد المالك والإدارة.

-- بعد الإعداد الأساسي شغّل أيضًا supabase/admin-enhancements.sql لتفعيل السلة والجدولة وتشديد صلاحيات الحذف.
